### ISSUE TITLE
Error: Unsupported protocol version: 1234.5679

### ISSUE THREAD

**Issue by 36ru** [oguimbal/pg-server#5] opened 2022-04-21 05:58 UTC
When connecting to the server, it says that the protocol version is not supported

**Comment by 36ru** [comment] 2022-04-21 06:05
Connecting with DataGrip

**Comment by paulbares** [comment] 2022-07-13 12:12
Same issue here with DataGrip:

```
Error: Unsupported protocol version: 1234.5679
    at CommandParser.parseInit (/Users/paul/dev/misc/pg-proxy-test/node_modules/src/protocol/command-parser.ts:223:19)
    at CommandParser.parse (/Users/paul/dev/misc/pg-proxy-test/node_modules/src/protocol/command-parser.ts:75:30)
    at Socket.<anonymous> (/Users/paul/dev/misc/pg-proxy-test/node_modules/src/server.ts:67:13)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
```

**Comment by prx0** [comment] 2022-08-24 09:50
Same issue here with psql.
```
psql postgresql://localhost:1234
```
```
[dev:*launch]             throw new Error(`Unsupported protocol version: ${major}.${minor}`);
[dev:*launch]             ^
[dev:*launch] 
[dev:*launch] Error: Unsupported protocol version: 1234.5679
[dev:*launch]     at CommandParser.parseInit (/home/maximilien/diskyver/pgproxy/node_modules/pg-server/protocol/command-parser.js:201:19)
[dev:*launch]     at CommandParser.parse (/home/maximilien/diskyver/pgproxy/node_modules/pg-server/protocol/command-parser.js:51:30)
[dev:*launch]     at Socket.<anonymous> (/home/maximilien/diskyver/pgproxy/node_modules/pg-server/server.js:41:13)
[dev:*launch]     at Socket.emit (node:events:527:28)
[dev:*launch]     at addChunk (node:internal/streams/readable:315:12)
[dev:*launch]     at readableAddChunk (node:internal/streams/readable:289:9)
[dev:*launch]     at Socket.Readable.push (node:internal/streams/readable:228:10)
[dev:*launch]     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

The typescript is from this example https://www.npmjs.com/package/pg-server#-usage-as-a-proxy

What should we do ?

**Comment by oguimbal** [comment] 2022-08-27 13:06
Hi ! 

Sorry for the delay :)

When a client asks for protocol version `1234.5679`, that means that this client (i.e. the software you're using) is asking for an SSL connection.

Unfortunately, SSL is not supported by pg-server at this time.
I cant dedicate more than a few hours every week to work on Open Source nowdays, and there are prerequisite work I want to finish to on [pg-mem](https://github.com/oguimbal/pg-mem) before resuming my work on pg-server (and possibly implementing SSL)

As a workaround, I would suggest to look for an option in the connection configuration of your client to disable SSL.

I'm closing this issue as a duplicate of #1

**Closed as completed by oguimbal** 2022-08-27 13:06 UTC

**Comment by prx0** [comment] 2022-08-27 21:07
> Hi ! 
> 
> Sorry for the delay :)
> 
> When a client asks for protocol version `1234.5679`, that means that this client (i.e. the software you're using) is asking for an SSL connection.
> 
> Unfortunately, SSL is not supported by pg-server at this time.
> I cant dedicate more than a few hours every week to work on Open Source nowdays, and there are prerequisite work I want to finish to on [pg-mem](https://github.com/oguimbal/pg-mem) before resuming my work on pg-server (and possibly implementing SSL)
> 
> As a workaround, I would suggest to look for an option in the connection configuration of your client to disable SSL.
> 
> I'm closing this issue as a duplicate of #1

Hi, thank you for the answer your project is great!

About this error I don't think I've tried to setup an encrypted connection using SSL.

As you can see in my previous comment, I used psql to setup a basic connection without ssl parameter in the postgresql url.

Are you sure that my psql command tried to setup a SSL connection ?

**Comment by oguimbal** [comment] 2022-08-28 10:20
I'm not a super expert of the pg protocol, but yes, it seems so.
The client seems to ask if the server supports SSL by requesting this protocol version. There may be a way to answer "I dont support SSL", but I dont know how (if you find info about that, please tell me so, or file a PR if you feel like it !)

Could you try ` sslmode=disable`, as specified in [psql doc](https://docs.postgresql.fr/10/app-psql.html) ?
